### ISSUE TITLE
Amazing work！Is there a certain timeline for the full dataset to be published?

### ISSUE THREAD

**Issue by WangKK1996** [aburns4/MoTIF#1]

**Comment by aburns4** [comment]
Hi, thank you for your interest in the data! My plan is finalize the data cleaning and code commenting for release in about 2 weeks. I will follow up here if I have any issues that would result in a delay for this timeline.

**Comment by aburns4** [comment]
Hi again, I have created a new generic, merged version of the MoTIF dataset that includes all of the action sequences and all data from the language collection portion of the annotation. 

I'll be updating the README on the main page of the repo in the coming days but here is the link to the data for you now https://drive.google.com/file/d/1_yT0QMUyogA-dS0ozBH8Q9Tn5pH9AdvE/view?usp=sharing

Thanks for your patience and let me know if you have any questions
