### ISSUE TITLE
There are some missing files when creating tfrecords with the released json file.

### ISSUE THREAD

**Issue by ZhiZZhang** [aburns4/MoTIF#3]
When I tried to run `sh make_motif_tfrecord.sh` to create the tfcords of MoTIF with your processed json file, I found there are some files missing in both raw data folders `traces_02_14_21` and `traces_03_17_21`. The names of missing files are as below:
11a1563e-130c-43c1-8692-8185b6abdfdf
21b03f3d-df57-4097-91b7-a63d1c133ad9
4b13fb47-9980-42d5-9aa8-ed2a76713ef6
54c14db2-f761-4583-aa1c-942ad60bdc5d
55b0ec86-c4c7-4e6a-b564-81aaed74f55f
6430af53-1ebe-4a6c-bbef-b609c657249b
67c20175-1d39-4f63-958f-727a0f4bc916

Besides, I also suffer from file missing when running `sh dedup.sh` to process the raw data.

Could you please double-check the integrity of the current released version and help fix these two issues? If there are some difference  between your released version and the one used for paper, could you please also double-check whether this difference in data will lead to performence gap when compared to the results in your paper? Many thanks!

**Comment by aburns4** [comment]
Here https://drive.google.com/file/d/1_yT0QMUyogA-dS0ozBH8Q9Tn5pH9AdvE/view?usp=sharing is a fixed larger version of the MoTIF data. It also includes data from additional traces and the language annotation, which weren't used in the splits for evaluating task automation.

I'll be updating the READMEs on the main page of the repo to describe metadata provided with each trace as well as update the data generation instructions to reflect this new raw data folder in the coming days.

I was able to successfully process the data (the dedup and tfrecord creation portions) with this new folder of raw data. Please confirm you are able to successfully use it!
