### ISSUE TITLE
AttributeError : Issues when pre-processing the raw data

### ISSUE THREAD

**Issue by 3rdCore** [aburns4/MoTIF#8]
Hello, 

I'm trying to process the raw data you provided by running the python script `all_in_one_motif_preprocess.py`. i just changed the dataset path and run the script as it is. The script started to parse the first file and then crashed due to an `AttributeError`, here is the related StackTrace : 

```python
Exception has occurred: AttributeError
'MoTIFSample' object has no attribute 'vh_w'
  File "C:\Users\Tom\Desktop\MoTIF\task_automation\seq2act\motif_data_generation\all_in_one_motif_preprocess.py", line 219, in __init__
    self.scale_x = self.im_w / self.vh_w
  File "C:\Users\Tom\Desktop\MoTIF\task_automation\seq2act\motif_data_generation\all_in_one_motif_preprocess.py", line 672, in main
    mysample = MoTIFSample(app, FLAGS.data_dir, trace, 'widget_exception_dims.json')
  File "C:\Users\Tom\Desktop\MoTIF\task_automation\seq2act\motif_data_generation\all_in_one_motif_preprocess.py", line 678, in <module>
    main()
AttributeError: 'MoTIFSample' object has no attribute 'vh_w'
```

The error is triggered while construction MoTIFSample object. This error is due to the fact that no screen dimensions can be found by the function `set_screen_dims` line 214 : 

`self.set_screen_dims()`

here is the related function : 

```python
    def set_screen_dims(self):
        trace = self.og_view_paths[0].split('\\')[-3]

        if trace in self.widget_exceptions:
            self.vh_w = int(self.widget_exceptions[trace][0])
            self.vh_h = int(self.widget_exceptions[trace][1])
        else:
            for view in self.og_view_paths:
                try:
                    with open(view, 'r') as f:
                        data = json.load(f)
                        bbox = data['activity']['root']['bounds']
                        width = bbox[2] - bbox[0]
                        height = bbox[3] - bbox[1]
                    if bbox[0] == 0 and bbox[1] == 0:
                        self.vh_w = width
                        self.vh_h = height
                        break
                except:
                    continue
```

Have you ever encountered this issue while parsing the raw data ? For a moment I thought I had a corrupted dataset, but I re-download the zipfile, and had the same problem. 

I also saw on the README, that already processed data is available somewhere, could you tell me where It can be downloaded?

**Comment by aburns4** [comment]
Hi there! It looks like you may have corrupted the function by accident? The first line should be
`trace = self.og_view_paths[0].split('/')[-3]`
but it looks like your code snippet is splitting on two backslashes instead.

For the processed data, yes, it is available: https://drive.google.com/file/d/1HD0nuFqAyapxmJiWj8Xhl3LeUDPVRIgm/view?usp=sharing - this link can be found under the README here https://github.com/aburns4/MoTIF/tree/main/task_automation/seq2act [apologies, there are many READMEs in this repo :)]

**Comment by 3rdCore** [comment]
Ho sorry, i should have mentioned this. I modified this part of the code, as I'm running this on Windows.

**Comment by aburns4** [comment]
Ah I see, gotcha. Do you mind printing out the trace within the `set_screen_dims` function and letting me know which sample it fails to assign the view hierarchy width and height for?
