### ISSUE TITLE
Cannot access to the raw data

### ISSUE THREAD

**Issue by pengyuanli** [aburns4/MoTIF#9]
Hi, can you help me to verify if the URL is still downloadable? 
 I received an error message when I tried to download the dataset.

**Comment by aburns4** [comment]
Hi! 

Sorry about that- I recently had to move all the files to a new Drive location due to storage issues. I have now uploaded all links in the READMEs accordingly.

Can you please try again? I will close the issue once you confirm it has been resolved.

Thanks,
Andrea

**Comment by aburns4** [comment]
Since I haven't heard an update and I have updated all of the links I will be closing this issue- feel free to reopen it as needed.
